# Site settings
title: Articles-SANSUIZ
email: xaiver_zhao@foxmail.com
description: A young man, thinking all the time
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wenji.sansuiz.cn" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username:  Sansuiz
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
future: true

# highlight
# use rouge locally, pygments in Github
# highlighter: pygments
# highlighter: rouge
# highlighter: false

timezone: Asia/Shanghai

# Giscus comment settings
giscus:
  repo: "Sansuiz/wenji"
  category: "Announcements" # Custom category on github discussion
  repo_id: "MDEwOlJlcG9zaXRvcnk0MDE3MzUzODg=" # Giscus generated repo id
  category_id: "DIC_kwDOF_H-3M4CdBge" # Giscus generated category id
  mapping: 'pathname'
  input_position: 'top'
  theme: 'light_tritanopia'
  lang: "zh-CN"